name: "Pull Request Deploy"
description: "A github action to automate the deployment of pull requests"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  server_host:
    description: SSH host of the server
    required: true
  server_username: 
    description: SSH username 
    required: true
  server_password:
    description: SSH password 
    required: true
  server_port:
    description: SSH port
    required: false
    default: 22
  context:
    description: Directory in the repository where the Dockerfile or start command is located
    required: false
    default: "./"
  dockerfile:
    description: Path to the Dockerfile (optional)
    required: false
    default: "./Dockerfile"
  exposed_port:
    description: Port to expose in the container
    required: true
  envs:
    description: Environment variables to pass to the container (multi-line string)
    required: false
  github_token:
    description: GitHub token to authenticate API requests
    required: true

outputs:
  preview-url:
    description: "Preview URL"
    value: ${{ steps.execute-deployment.outputs.preview-url }}

runs:
  using: 'composite'
  steps:
    - name: Docker Build
      shell: bash
      run: |
        PR_ID="pr_${{ github.event.repository.id }}_${{ github.event.number }}"
        cd "${{ inputs.context }}"
        docker build -t $PR_ID -f "${{ inputs.dockerfile }}" .
        docker save $PR_ID | gzip > "/tmp/${PR_ID}.tar.gz"
    - id: execute-deployment
      name: Execute deployment
      run: |
        cd ${{ github.action_path }} && bash entrypoint.sh
      shell: bash
      env:
        SERVER_HOST: ${{ inputs.server_host }}
        SERVER_USERNAME: ${{ inputs.server_username }}
        SERVER_PASSWORD: ${{ inputs.server_password }}
        SERVER_PORT: ${{ inputs.server_port }}
        CONTEXT: ${{ inputs.context }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        EXPOSED_PORT: ${{ inputs.exposed_port }}
        ENVS: ${{ inputs.envs }}
        REPO_URL: ${{ github.event.repository.clone_url }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PR_NUMBER: ${{ github.event.number }}
        PR_ACTION: ${{ github.event.action }}
        PR_ID: "pr_${{ github.event.repository.id }}_${{ github.event.number }}"
        GITHUB_TOKEN: ${{ inputs.github_token }}
