name: "Pull Request Deploy"
description: "A github action to automate the deployment of pull requests"
branding:
  icon: "cloud"
  color: "blue"

inputs:
  server_host:
    description: SSH host of the server
    required: true
  server_username: 
    description: SSH username 
    required: true
  server_password:
    description: SSH password 
    required: true
  server_port:
    description: SSH port
    required: true
  context:
    description: Directory in the repository where the Dockerfile or start command is located
    default: "./"
  dockerfile:
    description: Path to the Dockerfile (optional)
    required: false
  exposed_port:
    description: Port to expose in the container
    required: true
  envs:
    description: Environment variables to pass to the container
    required: false
  github_token:
    description: GitHub token to authenticate API requests
    required: true


runs:
  using: 'composite'
  steps:
    - name: Run entrypoint.sh
      run: |
        chmod +x ${{ github.action_path }}/entrypoint.sh
        ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        SERVER_HOST: ${{ inputs.server_host }}
        SERVER_USERNAME: ${{ inputs.server_username }}
        SERVER_PASSWORD: ${{ inputs.server_password }}
        SERVER_PORT: ${{ inputs.server_port }}
        CONTEXT: ${{ inputs.context }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        EXPOSED_PORT: ${{ inputs.exposed_port }}
        ENVS: ${{ inputs.envs }}
        REPO_URL: ${{ github.event.repository.clone_url }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PR_NUMBER: ${{ github.event.number }}
        PR_ACTION: ${{ github.event.action }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
