name: PR Deploy
on:
  pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Comment
        run: |
           curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -X POST \
           -d "{\"body\": \"Hello world\"}" \
           "https://api.github.com/repos/hngprojects/pr-deploy/issues/14/comments"

      - name: Deploy PR
        uses: ./
        with:
          server_host: ${{ secrets.SERVER_HOST }}
          server_username: ${{ secrets.SERVER_USERNAME }}
          server_password: ${{ secrets.SERVER_PASSWORD }}
          server_port: ${{ secrets.SERVER_PORT }}
          context: '.'
          dockerfile: 'Dockerfile'
          exposed_port: '5000'
          compose_file: 'docker-compose.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
